Fix for reference assemblies not working correctly
atifaziz/t5 pull request #2
Opened 2018-06-11 04:18 UTC by bittercoder

Today while attempting to using T5 for the first time, I found that referencing 3rd party assemblies like `Newtonsoft.Json` were not working.

It would fail to compile because it did not recognize the types from the assembly.

Upon further investigation I found that the references were not being included correctly when compiling with CSharpScript.

This PR should reproduce the issue and fix it.

2018-06-11 07:49 UTC, atifaziz requested changes
Thanks for the PR, especially including a test to exercise the issue. :+1: The only problem I have is bloating the repo with a permanent and large (641 KB) binary footprint of `Newtonsoft.Json.dll`. Can we go with getting that out of band and/or use something way smaller and leaner?

2018-06-11 07:49 UTC, atifaziz commented on tests/GenerationTests.cs
> +            gen.ReferencePaths.Add(TestContext.CurrentContext.TestDirectory);
Needs a space after `Add` just for style consistency with the lines above.

2018-06-11 10:49 UTC, bittercoder commented
Tidied the PR up to just use the json.net package's assembly location + normalized styling.  Let me know if your happy @atifaziz

2018-06-11 13:27 UTC, atifaziz approved these changes
I just made some polishing touch otherwise it's good. I guess the indirect dependency on Json.NET (via [Microsoft.NET.Test.Sdk](https://www.nuget.org/packages/Microsoft.NET.Test.Sdk/15.5.0) and [Microsoft.TestPlatform.TestHost](https://www.nuget.org/packages/Microsoft.TestPlatform.TestHost/15.5.0)) is okay and if it ever disappears from underneath when upgrading the package references then the test project won't compile and the problem can be addressed then.

Thanks again for the fix and the PR!

2018-06-11 13:31 UTC, merged

2018-06-11 18:46 UTC, bittercoder commented
Thanks @atifaziz - any chance of a new nuget package with the fix?

2018-06-12 11:16 UTC, atifaziz commented
> any chance of a new nuget package with the fix?

[Done!](https://github.com/atifaziz/t5/releases/tag/v1.1.0)