Added parameter expansion while evaluating include path
atifaziz/t5 pull request #6
Opened 2018-09-03 11:16 UTC by fredpointzero

This is usefull to have consistent include path between MSBuild and Visual Studio.

You can define an MSBuild property as the root directory for your include, it will be properly evaluated by Visual Studio's T4 Single-File generator and this property can be set as parameter in the command line of `dotnet tt`.

Example:
MSBuild file
```
<PropertyGroup>
    <MyRootInclude>SomePath\</MyRootInclude>
</PropertyGroup>
```

MyTemplate.tt
``` 
<#@ include file="$(MyRootInclude)MyIncludeFile.t4" #>
```

Dotnet cli
``` 
dotnet tt -a=MyRootInclude=SomePath\ MyTemplate.tt
```

2018-09-04 08:30 UTC, atifaziz requested changes
This looks like an interesting addition and thanks for the PR along with tests! It looks like, however, that db28598f5d7f2d750ad320bf20ab30e4536299e5 broke the build by introducing the following syntax errors:

```
EngineTests.cs(73,9): error CS0106: The modifier 'static' is not valid for this item [A:\T5\tests\T5.TextTemplating.Tests.csproj]
EngineTests.cs(82,11): error CS1513: } expected [A:\T5\tests\T5.TextTemplating.Tests.csproj]
```

2018-09-04 16:21 UTC, fredericvauchelles commented
@atifaziz  I missed a `}` while I was cleaning, causing the compile issue. I added a commit to fix it.

2018-09-07 12:44 UTC, atifaziz reviewed
Thanks but I think in 47cb375d56b9794652425917f32c405aa2749d8b, you also reverted changes from db28598f5d7f2d750ad320bf20ab30e4536299e5 so I reverted 47cb375d56b9794652425917f32c405aa2749d8b in ac35085a86d9f2168bbcbed3bc935261ef7fe89b and made just the necessary fix in ada3e5d3e28c0aad18600c133fd6080a956296cc. If you're okay with that then I'll go and merge this PR.

2018-09-12 12:57 UTC, fredpointzero commented
@atifaziz For sure, I am ok with that!

2018-09-12 17:01 UTC, atifaziz approved these changes

2018-09-12 19:13 UTC, merged